local EventFrame = CreateFrame("Frame")
EventFrame:RegisterEvent("PLAYER_LOGIN")
EventFrame:SetScript("OnEvent", function(self,event,...)
print("www.benice2.me")
PlayerFrame:ClearAllPoints()
PlayerFrame:SetPoint("CENTER","UIParent","CENTER",-175,-100)
PlayerFrame:SetUserPlaced(true)
TargetFrame:ClearAllPoints()
TargetFrame:SetPoint("CENTER","UIParent","CENTER",175,-100)
TargetFrame:SetUserPlaced(true)
end)